include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    unnecessary_await_in_return: false
    sort_pub_dependencies: false
    flutter_style_todos: false
    comment_references: false
    one_member_abstracts: false
    public_member_api_docs: false
    discarded_futures: false
